INSERT INTO WKF_INSTANCE(WKF_ID,UID,RES_ID,RES_TYPE,STATE)
(
SELECT (SELECT ID FROM WKF WHERE NAME='account.invoice.basic' AND OSV='account.invoice'),1,ID ,'account.invoice','active' 
	FROM ACCOUNT_INVOICE WHERE STATE='draft' AND MIGRATE=True
);

INSERT INTO WKF_WORKITEM(ACT_ID,INST_ID,STATE)
(SELECT 
	(SELECT ID FROM WKF_ACTIVITY WHERE WKF_ID IN (SELECT ID FROM WKF WHERE NAME='account.invoice.basic' AND OSV='account.invoice') AND 		NAME='open'),ID,'active' 
	FROM WKF_INSTANCE 
	WHERE WKF_ID=(SELECT ID FROM WKF WHERE NAME='account.invoice.basic' AND OSV='account.invoice')
	AND UID=1 AND RES_TYPE='account.invoice' AND STATE='active' AND RES_ID IN (SELECT ID FROM ACCOUNT_INVOICE WHERE STATE='draft' AND 		MIGRATE=True));

